from sqlalchemy import Column, Date, DateTime, ForeignKey, Integer, Numeric, String, func
from sqlalchemy.orm import relationship

from core.database import Base


class CustomerLoan(Base):
    __tablename__ = "customer_loans"

    id = Column(Integer, primary_key=True, autoincrement=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False, index=True)
    is_current = Column(Integer, default=0, index=True)
    application_id = Column(String(100), nullable=True, index=True)
    loan_number = Column(String(100), nullable=True, index=True)
    contract_number = Column(String(100), nullable=True, index=True)
    agreement_number = Column(String(100), nullable=True, index=True)
    product_type = Column(String(100), nullable=True)
    product_name = Column(String(100), nullable=True)
    platform_name = Column(String(100), nullable=True, index=True)
    disbursement_date = Column(Date, nullable=True)
    first_due_date = Column(Date, nullable=True)
    due_date = Column(Date, nullable=True, index=True)
    last_due_date = Column(Date, nullable=True)
    maturity_date = Column(Date, nullable=True)
    tenor = Column(Integer, nullable=True)
    installment_number = Column(Integer, nullable=True)
    remaining_installment_count = Column(Integer, nullable=True)
    payment_frequency = Column(String(50), nullable=True)
    loan_amount = Column(Numeric(18, 2), nullable=True)
    principal_amount = Column(Numeric(18, 2), nullable=True)
    interest_amount = Column(Numeric(18, 2), nullable=True)
    admin_fee_amount = Column(Numeric(18, 2), nullable=True)
    penalty_amount = Column(Numeric(18, 2), nullable=True)
    insurance_fee_amount = Column(Numeric(18, 2), nullable=True)
    other_fee_amount = Column(Numeric(18, 2), nullable=True)
    installment_amount = Column(Numeric(18, 2), nullable=True)
    outstanding_principal = Column(Numeric(18, 2), nullable=True)
    outstanding_interest = Column(Numeric(18, 2), nullable=True)
    outstanding_penalty = Column(Numeric(18, 2), nullable=True)
    outstanding_fee = Column(Numeric(18, 2), nullable=True)
    total_outstanding = Column(Numeric(18, 2), nullable=True)
    remaining_balance = Column(Numeric(18, 2), nullable=True)
    overdue_days = Column(Integer, nullable=True, index=True)
    days_past_due = Column(Integer, nullable=True, index=True)
    dpd_bucket = Column(String(50), nullable=True, index=True)
    aging_bucket = Column(String(50), nullable=True, index=True)
    bucket_code = Column(String(50), nullable=True, index=True)
    loan_status = Column(String(50), nullable=True, index=True)
    billing_status = Column(String(50), nullable=True, index=True)
    collection_stage = Column(String(50), nullable=True, index=True)
    risk_segment = Column(String(50), nullable=True, index=True)
    risk_score = Column(String(50), nullable=True)
    last_payment_date = Column(Date, nullable=True)
    last_payment_amount = Column(Numeric(18, 2), nullable=True)
    last_payment_channel = Column(String(100), nullable=True)
    last_payment_reference = Column(String(100), nullable=True)
    paid_amount_total = Column(Numeric(18, 2), nullable=True)
    payment_status = Column(String(50), nullable=True)
    promise_to_pay_date = Column(Date, nullable=True)
    promise_to_pay_amount = Column(Numeric(18, 2), nullable=True)
    promise_to_pay_status = Column(String(50), nullable=True)
    broken_ptp_count = Column(Integer, nullable=True)
    settlement_offer_amount = Column(Numeric(18, 2), nullable=True)
    settlement_expiry_date = Column(Date, nullable=True)
    minimum_payment_amount = Column(Numeric(18, 2), nullable=True)
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())

    customer = relationship("Customer", back_populates="loans", foreign_keys=[customer_id])
